version: '3'

services:
  # proxy:
  #   build: ./proxy
  #   ports:
  #     - "443:443"
  #   environment:
  #     - GATEWAY_IP=172.21.0.1
  #     - PORT=443

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    command: "certonly --standalone --agree-tos --preferred-challenges http -d slackuj.cz -m vithabada93@gmail.com"
    volumes:
        - ./letsencrypt:/etc/letsencrypt

  server:
    build: ./server
    ports:
      - "9090:9090"